wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698740132.381221
    t:
      1:
      - 1
      - 5
      - 6
      - 8
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
